# Form implementation generated from reading ui file 'KULLANİCİ.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class KULLANICI(object):
    def setupUi(self, qwidget):
        qwidget.setObjectName("qwidget")
        qwidget.resize(837, 533)
        self.kulllanicisayfa = QtWidgets.QGroupBox(parent=qwidget)
        self.kulllanicisayfa.setGeometry(QtCore.QRect(30, 20, 751, 471))
        self.kulllanicisayfa.setStyleSheet("background-color: rgb(32, 42, 64);")
        self.kulllanicisayfa.setTitle("")
        self.kulllanicisayfa.setObjectName("kulllanicisayfa")
        self.label = QtWidgets.QLabel(parent=self.kulllanicisayfa)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.kulllanicisayfa)
        self.pushButton.setGeometry(QtCore.QRect(580, 400, 151, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(152, 180, 210);\n"
"color: rgb(0, 87, 226);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(qwidget)
        QtCore.QMetaObject.connectSlotsByName(qwidget)

    def retranslateUi(self, qwidget):
        _translate = QtCore.QCoreApplication.translate
        qwidget.setWindowTitle(_translate("qwidget", "Form"))
        self.label.setText(_translate("qwidget", "Kullanıcı Sayfası_Dosyalar:"))
        self.pushButton.setText(_translate("qwidget", "ÇIKIŞ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qwidget = QtWidgets.QWidget()
    ui = KULLANICI()
    ui.setupUi(qwidget)
    qwidget.show()
    sys.exit(app.exec())
